[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "uvicorn app:app --host 0.0.0.0 --port 8000"
